### ISSUE TITLE
Encode non-english characters aswell

### ISSUE THREAD

**Issue by BrotherSharper** [BlitzKraig/fvtt-SoundBoard#35]
If the filename of a sound file is not in English alphabet it will bug out and instead show a long line of gibberish. See image below
![image](https://user-images.githubusercontent.com/41280723/112951173-09b5a600-9176-11eb-9b1c-c96090f9d5e1.png)

**Comment by BlitzKraig** [comment]
Hi BrotherSharper,
I believe this will be fixed in the next release.
I have just tested with ソードヒット.wav (google translated), which is appearing as in this image:
![image](https://user-images.githubusercontent.com/5331089/112959517-6a73bd00-913b-11eb-8053-40c45411a1ab.png)

Does this all seem right? Any other gotcha's I might be missing?

**Comment by BrotherSharper** [comment]
> 
> 
> Hi BrotherSharper,
> I believe this will be fixed in the next release.
> I have just tested with ソードヒット.wav (google translated), which is appearing as in this image:
> ![image](https://user-images.githubusercontent.com/5331089/112959517-6a73bd00-913b-11eb-8053-40c45411a1ab.png)
> 
> Does this all seem right? Any other gotcha's I might be missing?

That is perfect, thank you for addressing this!

**Comment by BlitzKraig** [comment]
Thanks, closing as fixed in 1.2.1
