### ISSUE TITLE
Sounds don't play when soundboard is "popped out"

### ISSUE THREAD

**Issue by Tutunkommon** [BlitzKraig/fvtt-SoundBoard#40]
Just installed and noticed that there are no sounds when I pop-out the soundboard.  When it is pop-in again, they work as normal.

**Comment by BlitzKraig** [comment]
Hi, I've not tested PopOut!, so will need to take a look and see if I can make it compatible.

Thanks for the feedback

**Comment by BlitzKraig** [comment]
Had a look at this - clicking a sound before popping out causes the sound to be available after popping out...

I was able to have the whole SoundBoard work after altering the popout code to stop it from stripping out a bunch of extra header information. I assume KaKaRoTo does this for performance reasons (otherwise everything is being re-loaded into the popout window)

My gut feeling is that SoundBoard is doing something wrong, and should be passing some more data into the Application that PopOut! will handle correctly - I'll try to find some time to have a chat with KaKaRoTo, but I'm aware he's very busy at the moment.

**Comment by BlitzKraig** [comment]
There's a new experimental option in 1.4.0 that should allow PopOut! to work, though it may cause some performance issues, and might not play nice with certain modules.

Give it a try and let me know if it does the job

**Comment by BlitzKraig** [comment]
Closing as no feedback received
